version: "3"
services:
  
  appsample:
    image: golang:1.10-alpine
    container_name: appsample
    environment:
      - DEPNOLOCK=1
    volumes:
      - ../../workspace:/go
    working_dir: /go/src/appsample
    command: >
      sh -c  "ls /go/scripts/setup.sh && 
              /go/scripts/setup.sh &&     # long time setup, only at very first clone project but you can fixed by create your own image
              touch /tmp/systemready &&   # to check is system ready to use
              sleep 28800"                # 60*60*8: 8 hours 
